package br.eti.allandemiranda.forex.headers;

public enum OrderHeader {
  OPEN_DATE_TIME, LAST_UPDATE, OPEN_CANDLE_DATE_TIME, LAST_CANDLE_UPDATE, STATUS, POSITION, OPEN_PRICE, CLOSE_PRICE, TIME, HIGH_PROFIT, LOW_PROFIT, CURRENT_PROFIT, CURRENT_BALANCE
}