package br.eti.allandemiranda.forex.headers;

public enum OrderHeader {
  OPEN_DATE_TIME, SIGNAL_DATE_TIME, SIGNAL_TREND, LAST_UPDATE_DATE_TIME, OPEN_TIME, ORDER_STATUS, ORDER_POSITION, OPEN_PRICE, CLOSE_PRICE, HIGH_PROFIT, LOW_PROFIT, CURRENT_PROFIT, SWAP_PROFIT, CURRENT_BALANCE, OPEN_DAY_WEEK, OPEN_DAY_HOURS
}