package br.eti.allandemiranda.forex.headers;

public enum SignalHeader {
  CANDLE_DATE_TIME, OPEN, HIGH, LOW, CLOSE, TREND_BUY, TREND_SELL, TREND_NEUTRAL, INDICATORS_BUY, INDICATORS_SELL, INDICATORS_NEUTRAL

}